version: '3.8'

name: ai-agent

services:
  fetcher-mcp:
    image: ghcr.io/jae-jae/fetcher-mcp:latest
    container_name: fetcher-mcp
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /tmp:/tmp
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - my-network

  mcp-server-csdn-app:
    image: registry.cn-hangzhou.aliyuncs.com/fuzhengwei/mcp-server-csdn-app:1.1
    container_name: mcp-server-csdn-app
    restart: always
    ports:
      - "8101:8101"
    volumes:
      - ./log:/data/log
    environment:
      - TZ=PRC
      - SERVER_PORT=8101
      - CSDN_API_CATEGORIES=Java
      - CSDN_API_COOKIE=uuid_tt_dd=10_30290024670-1766903047254-493402
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network
  xiaohongshu-mcp:
    image: xpzouying/xiaohongshu-mcp
    container_name: xiaohongshu-mcp
    restart: unless-stopped
    init: true
    tty: true
    volumes:
      - ./data:/app/data
      - ./images:/app/images
    environment:
      - ROD_BROWSER_BIN=/usr/bin/google-chrome
      - COOKIES_PATH=/app/data/cookies.json
    ports:
      - "18060:18060"
networks:
  my-network:
    driver: bridge